{
 "title": "Amazon EC2",
 "description": "Visualize Amazon EC2 metrics",
 "tags": [
  "Amazon",
  "AWS",
  "CloudWatch",
  "EC2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  {
   "title": "Memory Used -EC2 WindowsServices instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-02f117f3e76d5f21a" },
     "metricName": "MemoryUsed",
     "namespace": "Windows System",
     "region": "us-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "description": "Memory available on EC2 WindowsServices instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "i-02f117f3e76d5f21a" },
     "metricName": "MemoryUsed",
     "namespace": "Windows System",
     "region": "us-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Services Status Check",
   "type": "graph",
   "description": "This panel shows the status of Services deployed on PlayerMaxWindowsServices instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "instanceid": "i-02f117f3e76d5f21a", "service": "*" },
     "metricName": "Status",
     "namespace": "Three-services-monitor",
     "region": "us-west-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU utilization per instance [max %]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Total network traffic outbound (+) and inbound (-) [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "dimensions": { "InstanceId": "*" },
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkIn\"', 'Sum', $period)))/$period",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Outbound",
     "dimensions": { "InstanceId": "*" },
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkOut\"', 'Sum', $period)))/$period",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Network details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound network traffic per instance [bytes/sec]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkIn\"', 'Sum', $period))/$period",
       "metricName": "NetworkIn",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Outbound network traffic per instance [bytes/sec]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkOut\"', 'Sum', $period))/$period",
       "metricName": "NetworkIn",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Inbound network packets per instance [IOPS]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkPacketsIn\"', 'Sum', $period))/$period",
       "metricName": "NetworkPacketsIn",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Outbound network packets per instance [IOPS]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkPacketsOut\"', 'Sum', $period))/$period",
       "metricName": "NetworkPacketsIn",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "The following metrics are reported for EC2 Instance Store Volumes. For Amazon EBS volumes, see the EBS dashboard.",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
    },
    {
     "title": "Disk READ per instance [bytes/sec]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{label}}",
       "dimensions": { "InstanceId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"DiskReadBytes\"', 'Sum', $period))/$period",
       "metricName": "DiskReadBytes",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Disk WRITE per instance [bytes/sec]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{label}}",
       "dimensions": { "InstanceId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"DiskWriteBytes\"', 'Sum', $period))/$period",
       "metricName": "DiskReadBytes",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Disk READ per instance [IOPS]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{label}}",
       "dimensions": { "InstanceId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"DiskReadOps\"', 'Sum', $period))/$period",
       "metricName": "DiskReadBytes",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Disk WRITE per instance [IOPS]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{label}}",
       "dimensions": { "InstanceId": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"DiskWriteOps\"', 'Sum', $period))/$period",
       "metricName": "DiskReadBytes",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Status Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status check failed [Sum]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "*" },
       "metricName": "StatusCheckFailed",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Instance status check failed [Sum]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "*" },
       "metricName": "StatusCheckFailed",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "System status check failed [Sum]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "*" },
       "metricName": "StatusCheckFailed",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    }
   ]
  },
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 46 },
   "content": "For more information about avaialble metrics from Amazon EC2, visit the [List of Available CloudWatch Metrics for Your EC2 Instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html) in the Amazon documentation.\n\nFor additional metrics and 1-minute granularity, enable [Detailed Monitoring](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-cloudwatch-new.html) for your Amazon EC2 instances.\n\nThis dashboard has been optimized for 1-minute metrics.",
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  }
 ]
}